# Site Settings
title: Start Jekyll
email: friendsofsullivan@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://friendsofsullivan.github.io"
twitter_username: friendsofsullivan
github_username:  friendsofsullivan
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM